# For more information see: 
#  https://docs.github.com/en/actions/automating-builds-and-tests/

name: build

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5 1 */3 *'
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - "ubuntu-20.04"
          - "ubuntu-22.04"
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libvncserver-dev cmake qt5-qmake qtbase5-dev
    - name: Test CMake build
      run: |
        mkdir -p build && cd build && cmake .. && make && cd ..
    - name: Test QT build
      run: |
        mkdir -p buildqt && cd buildqt && qmake ../framebuffer-vncserver.pro && make && cd ..
